name: Main

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare
        run: sudo apt install clang lld
      - name: Build
        run: ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./bin/crafter-build